version: "3"
services:
  app:
    build:
      context: .
      dockerfile: test.dockerfile
    container_name: yue
    stdin_open: true
    tty: true
    depends_on:
      - database
    environment:
      BASE_PATH: /app
      DEBUG: true
  database:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_DATABASE: Yue
      MYSQL_USER: Yue
      MYSQL_PASSWORD: test
      MARIADB_ROOT_PASSWORD: test
